---
name: Variables
locale: es
type: practice
beta: false
teacher_info: |-
  # Objetivos principales

  * Presentar a las variables como una forma de ponerle nombre a un valor para usarlo más tarde.
  * Mostrar su utilidad para funciones donde hay que devolver cosas diferentes dependiendo de una condición.
  * Cómo usar variables para implementar un contador, acumulador (suma), máximo y mínimo

  # Objetivos secundarios
language: gobstones
id_format: '%05d'
order:
- 4
- 1
- 2
- 6
- 3
- 5
- 7
- 8
- 9
