---
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Rojo
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Verde
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: colorcito
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 'True'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: 'False'
  checked: false
name: Otra etiqueta...
